### ISSUE TITLE
'contours_rec' is not defined

### ISSUE THREAD

**Issue by rubiquinones** [Computational-Plant-Science/SMART#10]
There is a variable error when trying to run the sample rosette.jpg image provided in the project: 

I run the following code: 

`python3 core/color_seg.py -p media/rosette.jpg -r output`
`python3 core/trait_extract_parallel_ori.py -p media/rosette.jpg -r output -l`

and it gives this error:

Traceback (most recent call last):
  File "core/trait_extract_parallel_ori.py", line 1116, in <module>
    extract_traits(path, result_path, leaves, multi)
  File "core/trait_extract_parallel_ori.py", line 1080, in extract_traits
    leaf_color_ratio_rec, leaf_color_value_rec, box_coord_rec) = leaf_traits_computation(image_copy, labels, output_directory, base_name)
  File "core/trait_extract_parallel_ori.py", line 595, in leaf_traits_computation
    contours_rec.append(c)
NameError: name 'contours_rec' is not defined

**Comment by lsx1980** [comment]
Hi plz update the Github to the latest version, it should be fixed by now. Thanks!
